import LayoutAdmin from "@/components/pageAdmin/LayoutAdmin";
import Head from "next/head";

const Admin = () => {
  return (
    <>
      <Head>
        <title>Página do administrador</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutAdmin />
    </>
  );
};
export default Admin;
