import LayoutAdmin from "@/components/pageAdmin/LayoutAdmin";
import PanelUsers from "@/components/pageAdmin/clientsPage/PanelUsers";
import Head from "next/head";

const Clientes = () => {
  return (
    <>
      <Head>
        <title>Cadastros</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutAdmin>
        <PanelUsers />
      </LayoutAdmin>
    </>
  );
};
export default Clientes;
