import LayoutAdmin from "@/components/pageAdmin/LayoutAdmin";
import ElementsPortfolio from "@/components/pageAdmin/portfolioPage/PortfolioEdit";
import Head from "next/head";

const PortfolioEdit = () => {
  return (
    <>
      <Head>
        <title>Cadastro de projetos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutAdmin>
        <ElementsPortfolio />
      </LayoutAdmin>
    </>
  );
};
export default PortfolioEdit;
