import LayoutAdmin from "@/components/pageAdmin/LayoutAdmin";
import SocialProof from "@/components/pageAdmin/socialPage/SocialProof";
import Head from "next/head";

const Social = () => {
  return (
    <>
      <Head>
        <title>Prova social</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutAdmin>
        <SocialProof />
      </LayoutAdmin>
    </>
  );
};
export default Social;
