import LayoutAdmin from "@/components/pageAdmin/LayoutAdmin";
import SocialProof from "@/components/pageAdmin/socialPage/SocialProof";
import Head from "next/head";
import { verifyToken } from "../../../services/user";
import { getCookie } from "cookies-next";

const Social = () => {
  return (
    <>
      <Head>
        <title>Prova social</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutAdmin>
        <SocialProof />
      </LayoutAdmin>
    </>
  );
};
export default Social;

export const getServerSideProps = async ({ req, res }) => {
  try {
    const token = getCookie("authorization", {req, res});
    if(!token) throw new Error ("Token inválido");
    verifyToken(token)
    return {
      props: {},
    };
  } catch (err) {
    return {
      redirect: {
        permanent: false,
        destination: "/secret-page/login"
      },
      props: {},
    };
  }
};